apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaMirrorMaker2
metadata:
  name: my-mirror-maker2
spec:
  version: 2.4.0
  connectCluster: "my-cluster-target"
  clusters:
    - alias: "my-cluster-source"
      bootstrapServers: my-cluster-kafka-bootstrap.kafka-playground.svc:9092
    - alias: "my-cluster-target"
      bootstrapServers: my-target-cluster-kafka-bootstrap.kafka-target.svc:9092
  mirrors:
    - sourceCluster: "my-cluster-source"
      targetCluster: "my-cluster-target"
      sourceConnector: {}
      topicsPattern: ".*"